[package]
name = "aqua"
version = "0.0.0-AFTER"
edition = "2021"

[dependencies]
bytes = "1"
smallvec = "1"
dashmap = "6"
quinn = "0.11"
anyhow = "1"

[dependencies.tokio]
version = "1"
default-features = false
features = ["sync", "rt"]
